name: ci

on:
  push:
    paths:
      - "**.f90"
      - ".github/workflows/ci.yml"
      - "CMakeLists.txt"
  pull_request:
    paths:
      - "**.f90"
      - ".github/workflows/ci.yml"
      - "CMakeLists.txt"

jobs:

  windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          git
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-ninja
          mingw-w64-x86_64-gcc-fortran
    - uses: actions/checkout@v3

    - run: cmake -B build -G Ninja
    - run: cmake --build build
    - run: ctest --test-dir build -V

  core:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: macOS Gfortran setup
      if: runner.os == 'macOS'
      run: brew reinstall gcc

    - run: cmake -B build
    - run: cmake --build build
    - run: ctest --test-dir build -V
